# Autogenerated wrapper script for poly2tri_jll for x86_64-w64-mingw32-cxx03
export libpoly2tri

JLLWrappers.@generate_wrapper_header("poly2tri")
JLLWrappers.@declare_library_product(libpoly2tri, "libpoly2tri.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpoly2tri,
        "bin\\libpoly2tri.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
